### ISSUE TITLE
Download too slow?

### ISSUE THREAD

**Issue by TheShadow29** [BayesWatch/cinic-10#3]
Thank you for the amazing dataset. 

The default download option is taking too much time (took around 45min to download the dataset). I am wondering if a google drive / dropbox mirror link would be more appropriate (on my side it took < 10s to download from personal drive). Especially, since the dataset is not very large.

Thank you for your patience.

**Comment by learning-luke** [comment]
You're most welcome. I just tested the download and it completed in approximately 17 seconds. This is likely because I'm geographically closer to the dataset, or it might be that you're much further away. Nonetheless, 45 minutes seems strangely long.

If you would like to host the dataset on your own Google Drive or Dropbox account and share that location, feel free to do so. As it is, unless this is a persistent issue (which it doesn't seem to be as of yet), we'll be sticking with Edinburgh DataShare.

**Comment by TheShadow29** [comment]
Great. I have hosted it on my drive account here: https://drive.google.com/open?id=1OhJuW5Oohy6m9Wb2pipReH_3ZCEkz-6l

I re-tried and am facing similar download times, so I guess the location is the problem.
